server:
  port: 8081

spring:
  application:
    name: chat-server
  websocket:
      path: /ws
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://192.168.100.21:8080/realms/chat_server
  data:
      cassandra:
        contact-points: 127.0.0.1
        port: 9042
        local-datacenter: datacenter1
        keyspace-name: chat_server
        username: cassandra
        password: cassandrapassword123
        schema-action: create-if-not-exists

      redis:
        host: localhost
        port: 6379
        password: redispassword123

  rabbitmq:
      port: 5672
      host: localhost
      username: admin
      password: rabbitpassword123
      stomp-port: 61613


keycloak:
  realm: icp-dev
  auth:
    server:
      url: http://192.168.100.21:8080
  openid-connect-url: http://192.168.100.21:8080/realms/master/.well-known/openid-configuration

auth:
  server:
    client:
      id: chat_server
